/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WorktreeBySessionRequest, WorktreeCreateRequest, WorktreeCreateResult, WorktreeDeleteRequest, WorktreeDeleteResult, WorktreeListRequest, WorktreeListResult, WorktreeResolveRequest, WorktreeResolveResult } from '@killertux/dsh-clemento-worktree/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$776f726b747265655265676973747279 {
    bySession: (request: WorktreeBySessionRequest) => Promise<RemoteResult<WorktreeResolveResult>>
    create: (request: WorktreeCreateRequest) => Promise<RemoteResult<WorktreeCreateResult>>
    delete: (request: WorktreeDeleteRequest) => Promise<RemoteResult<WorktreeDeleteResult>>
    discover: (request: WorktreeListRequest) => Promise<RemoteResult<WorktreeListResult>>
    list: (request: WorktreeListRequest) => Promise<RemoteResult<WorktreeListResult>>
    resolve: (request: WorktreeResolveRequest) => Promise<RemoteResult<WorktreeResolveResult>>
  }
  interface TypertRemoteMap {
    'worktreeRegistry/bySession': (request: WorktreeBySessionRequest) => Promise<RemoteResult<WorktreeResolveResult>>
    'worktreeRegistry/create': (request: WorktreeCreateRequest) => Promise<RemoteResult<WorktreeCreateResult>>
    'worktreeRegistry/delete': (request: WorktreeDeleteRequest) => Promise<RemoteResult<WorktreeDeleteResult>>
    'worktreeRegistry/discover': (request: WorktreeListRequest) => Promise<RemoteResult<WorktreeListResult>>
    'worktreeRegistry/list': (request: WorktreeListRequest) => Promise<RemoteResult<WorktreeListResult>>
    'worktreeRegistry/resolve': (request: WorktreeResolveRequest) => Promise<RemoteResult<WorktreeResolveResult>>
  }
  interface TypertRemoteNamespaceMap {
    'worktreeRegistry': TypertRemoteNamespace$776f726b747265655265676973747279
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
