/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_worktree_worktreeRegistry_bySession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_bySession_result$schema = z.object({
  'worktree': z.union([z.literal(null), z.object({
  'worktreeId': z.intersection(z.string(), z.unknown()),
  'workspaceId': z.intersection(z.string(), z.unknown()),
  'path': z.string(),
  'name': z.string(),
  'isMain': z.boolean(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})]),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_create_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()),
  'branch': z.string(),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_create_result$schema = z.object({
  'worktree': z.object({
  'worktreeId': z.intersection(z.string(), z.unknown()),
  'workspaceId': z.intersection(z.string(), z.unknown()),
  'path': z.string(),
  'name': z.string(),
  'isMain': z.boolean(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())),
  'createdAt': z.string(),
  'updatedAt': z.string(),
}),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_delete_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()),
  'worktreeId': z.intersection(z.string(), z.unknown()),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_delete_result$schema = z.object({
  'deleted': z.boolean(),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_discover_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_discover_result$schema = z.object({
  'items': z.array(z.object({
  'worktreeId': z.intersection(z.string(), z.unknown()),
  'workspaceId': z.intersection(z.string(), z.unknown()),
  'path': z.string(),
  'name': z.string(),
  'isMain': z.boolean(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_list_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_list_result$schema = z.object({
  'items': z.array(z.object({
  'worktreeId': z.intersection(z.string(), z.unknown()),
  'workspaceId': z.intersection(z.string(), z.unknown()),
  'path': z.string(),
  'name': z.string(),
  'isMain': z.boolean(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_mapBySessions_parameter_0$schema = z.object({
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_mapBySessions_result$schema = z.object({
  'mappings': z.record(z.string(), z.intersection(z.string(), z.unknown())),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_resolve_parameter_0$schema = z.object({
  'cwd': z.string(),
})
const _deepseek_ai_dsh_worktree_worktreeRegistry_resolve_result$schema = z.object({
  'worktree': z.union([z.literal(null), z.object({
  'worktreeId': z.intersection(z.string(), z.unknown()),
  'workspaceId': z.intersection(z.string(), z.unknown()),
  'path': z.string(),
  'name': z.string(),
  'isMain': z.boolean(),
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())),
  'createdAt': z.string(),
  'updatedAt': z.string(),
})]),
})

export const TYPERT = {
  package: '@killertux/dsh-clemento-worktree',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@killertux/dsh-clemento-worktree#worktreeRegistry/bySession',
      service: 'worktreeRegistry',
      namespace: 'worktreeRegistry',
      method: 'bySession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeBySessionRequest',
            schema: _deepseek_ai_dsh_worktree_worktreeRegistry_bySession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeResolveResult',
        schema: _deepseek_ai_dsh_worktree_worktreeRegistry_bySession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/worktree/src/index.ts","line":256,"column":9},
    },
    {
      id: '@killertux/dsh-clemento-worktree#worktreeRegistry/create',
      service: 'worktreeRegistry',
      namespace: 'worktreeRegistry',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeCreateRequest',
            schema: _deepseek_ai_dsh_worktree_worktreeRegistry_create_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeCreateResult',
        schema: _deepseek_ai_dsh_worktree_worktreeRegistry_create_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/worktree/src/index.ts","line":168,"column":9},
    },
    {
      id: '@killertux/dsh-clemento-worktree#worktreeRegistry/delete',
      service: 'worktreeRegistry',
      namespace: 'worktreeRegistry',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeDeleteRequest',
            schema: _deepseek_ai_dsh_worktree_worktreeRegistry_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeDeleteResult',
        schema: _deepseek_ai_dsh_worktree_worktreeRegistry_delete_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/worktree/src/index.ts","line":188,"column":9},
    },
    {
      id: '@killertux/dsh-clemento-worktree#worktreeRegistry/discover',
      service: 'worktreeRegistry',
      namespace: 'worktreeRegistry',
      method: 'discover',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeListRequest',
            schema: _deepseek_ai_dsh_worktree_worktreeRegistry_discover_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeListResult',
        schema: _deepseek_ai_dsh_worktree_worktreeRegistry_discover_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/worktree/src/index.ts","line":209,"column":9},
    },
    {
      id: '@killertux/dsh-clemento-worktree#worktreeRegistry/list',
      service: 'worktreeRegistry',
      namespace: 'worktreeRegistry',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeListRequest',
            schema: _deepseek_ai_dsh_worktree_worktreeRegistry_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeListResult',
        schema: _deepseek_ai_dsh_worktree_worktreeRegistry_list_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/worktree/src/index.ts","line":154,"column":9},
    },
    {
      id: '@killertux/dsh-clemento-worktree#worktreeRegistry/mapBySessions',
      service: 'worktreeRegistry',
      namespace: 'worktreeRegistry',
      method: 'mapBySessions',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeMapSessionsRequest',
            schema: _deepseek_ai_dsh_worktree_worktreeRegistry_mapBySessions_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeMapSessionsResult',
        schema: _deepseek_ai_dsh_worktree_worktreeRegistry_mapBySessions_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/worktree/src/index.ts","line":279,"column":9},
    },
    {
      id: '@killertux/dsh-clemento-worktree#worktreeRegistry/resolve',
      service: 'worktreeRegistry',
      namespace: 'worktreeRegistry',
      method: 'resolve',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeResolveRequest',
            schema: _deepseek_ai_dsh_worktree_worktreeRegistry_resolve_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@killertux/dsh-clemento-worktree/types#WorktreeResolveResult',
        schema: _deepseek_ai_dsh_worktree_worktreeRegistry_resolve_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/worktree/src/index.ts","line":238,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable worktree registry. Startup waits for session persistence and the workspace registry, indexes session headers by canonical cwd, and mints main-worktree records for git workspaces before the service becomes active. Live session creation is adopted through `session/created`.",
        "summary": "Durable worktree registry.",
        "tags": [],
        "jsDoc": "/**\n * Durable worktree registry. Startup waits for session persistence and the\n * workspace registry, indexes session headers by canonical cwd, and mints\n * main-worktree records for git workspaces before the service becomes\n * active. Live session creation is adopted through `session/created`.\n */",
        "key": "worktreeRegistry",
        "exportName": "WorktreeRegistry",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(request: WorktreeListRequest): Promise<WorktreeListResult>",
            "summary": "The wire read face: durable worktree records of one workspace, main worktree first, in registry order.",
            "jsDoc": "/**\n * The wire read face: durable worktree records of one workspace, main\n * worktree first, in registry order.\n * @param request - the owning workspace.\n * @returns the workspace's worktree views.\n */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote('create') async create(request: WorktreeCreateRequest): Promise<WorktreeCreateResult>",
            "summary": "Create a linked worktree on a NEW branch: runs `git worktree add` at the default sibling path, then records the resulting directory durably.",
            "jsDoc": "/**\n * Create a linked worktree on a NEW branch: runs `git worktree add` at the\n * default sibling path, then records the resulting directory durably.\n * @param request - the owning workspace (must be a git worktree) and the new branch name.\n * @returns the created worktree view.\n * @throws when the workspace is not a git worktree or git rejects the branch.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') async delete(request: WorktreeDeleteRequest): Promise<WorktreeDeleteResult>",
            "summary": "Remove a linked worktree: runs `git worktree remove --force`, then deletes the durable record.",
            "jsDoc": "/**\n * Remove a linked worktree: runs `git worktree remove --force`, then deletes\n * the durable record. The main worktree can never be removed.\n * @param request - the owning workspace and the linked worktree to remove.\n * @returns `deleted: true` when a record was deleted, `false` when it was unknown.\n */"
          },
          {
            "kind": "method",
            "name": "discover",
            "signature": "@Remote('discover') async discover(request: WorktreeListRequest): Promise<WorktreeListResult>",
            "summary": "Re-sync durable records with `git worktree list`: adopt newly discovered linked worktrees and prune records whose directory git no longer lists.",
            "jsDoc": "/**\n * Re-sync durable records with `git worktree list`: adopt newly discovered\n * linked worktrees and prune records whose directory git no longer lists.\n * @param request - the owning workspace.\n * @returns the refreshed worktree views.\n */"
          },
          {
            "kind": "method",
            "name": "resolve",
            "signature": "@Remote('resolve') async resolve(request: WorktreeResolveRequest): Promise<WorktreeResolveResult>",
            "summary": "The worktree containing a directory, for the session badge: any cwd maps to at most one registered worktree path.",
            "jsDoc": "/**\n * The worktree containing a directory, for the session badge: any cwd maps\n * to at most one registered worktree path.\n * @param request - a directory path in any spelling.\n * @returns the matching worktree view, or null when none matches.\n */"
          },
          {
            "kind": "method",
            "name": "bySession",
            "signature": "@Remote('bySession') async bySession(request: WorktreeBySessionRequest): Promise<WorktreeResolveResult>",
            "summary": "The worktree accounting a session, resolving the session's header cwd on demand when the index has not seen it yet.",
            "jsDoc": "/**\n * The worktree accounting a session, resolving the session's header cwd\n * on demand when the index has not seen it yet.\n * @param request - the session to locate.\n * @returns the worktree view, or null when the session is in no worktree.\n */"
          },
          {
            "kind": "method",
            "name": "mapBySessions",
            "signature": "@Remote('mapBySessions') async mapBySessions(request: WorktreeMapSessionsRequest): Promise<WorktreeMapSessionsResult>",
            "summary": "The owning workspace of each indexed session whose cwd matches a registered worktree, for the sidebar grouping of worktree sessions.",
            "jsDoc": "/**\n * The owning workspace of each indexed session whose cwd matches a\n * registered worktree, for the sidebar grouping of worktree sessions.\n * @param request - sessions to map.\n * @returns session id → owning workspace id (indexed sessions only).\n */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "get(id: WorktreeId): Worktree | undefined",
            "summary": "Look up a worktree by id.",
            "jsDoc": "/**\n * Look up a worktree by id.\n * @param id - Worktree id.\n * @returns the worktree, or `undefined` when unknown.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          },
          {
            "name": "Worktree",
            "declaration": "export interface Worktree {\n    readonly id: WorktreeId;\n    readonly workspaceId: WorkspaceId;\n    readonly path: string;\n    readonly name: string;\n    readonly isMain: boolean;\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly sessionIds: readonly SessionId[];\n    setName(name: string): Promise<void>;\n    attachSession(sessionId: SessionId): Promise<void>;\n    insertSessionBefore(sessionId: SessionId, beforeSessionId?: SessionId): Promise<void>;\n    detachSession(sessionId: SessionId): Promise<void>;\n    status(): Promise<'ok' | 'missing-dir'>;\n}"
          },
          {
            "name": "WorktreeBySessionRequest",
            "declaration": "export interface WorktreeBySessionRequest {\n    sessionId: SessionId;\n}"
          },
          {
            "name": "WorktreeCreateRequest",
            "declaration": "export interface WorktreeCreateRequest {\n    workspaceId: WorkspaceId;\n    branch: string;\n}"
          },
          {
            "name": "WorktreeCreateResult",
            "declaration": "export interface WorktreeCreateResult {\n    worktree: WorktreeView;\n}"
          },
          {
            "name": "WorktreeDeleteRequest",
            "declaration": "export interface WorktreeDeleteRequest {\n    workspaceId: WorkspaceId;\n    worktreeId: WorktreeId;\n}"
          },
          {
            "name": "WorktreeDeleteResult",
            "declaration": "export interface WorktreeDeleteResult {\n    deleted: boolean;\n}"
          },
          {
            "name": "WorktreeId",
            "declaration": "export type WorktreeId = WorktreeIdBrand;"
          },
          {
            "name": "WorktreeId",
            "declaration": "export type WorktreeId = Branded<'WorktreeId'>;"
          },
          {
            "name": "WorktreeListRequest",
            "declaration": "export interface WorktreeListRequest {\n    workspaceId: WorkspaceId;\n}"
          },
          {
            "name": "WorktreeListResult",
            "declaration": "export interface WorktreeListResult {\n    items: WorktreeView[];\n}"
          },
          {
            "name": "WorktreeMapSessionsRequest",
            "declaration": "export interface WorktreeMapSessionsRequest {\n    sessionIds: SessionId[];\n}"
          },
          {
            "name": "WorktreeMapSessionsResult",
            "declaration": "export interface WorktreeMapSessionsResult {\n    mappings: Record<string, WorkspaceId>;\n}"
          },
          {
            "name": "WorktreeResolveRequest",
            "declaration": "export interface WorktreeResolveRequest {\n    cwd: string;\n}"
          },
          {
            "name": "WorktreeResolveResult",
            "declaration": "export interface WorktreeResolveResult {\n    worktree: WorktreeView | null;\n}"
          },
          {
            "name": "WorktreeView",
            "declaration": "export interface WorktreeView {\n    worktreeId: WorktreeId;\n    workspaceId: WorkspaceId;\n    path: string;\n    name: string;\n    isMain: boolean;\n    sessionIds: SessionId[];\n    createdAt: string;\n    updatedAt: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
